version: '3.8'

services:
  youtube-processor:
    build: .
    container_name: aimara-processor
    volumes:
      # Mount entire app directory for hot-reload during development
      - .:/app
    environment:
      - PYTHONPATH=/app
    stdin_open: true
    tty: true
    # Uncomment below for GPU support (requires nvidia-docker2)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]